<a href="https://colab.research.google.com/github/marinhotechdev/InteligenciaArtificial/blob/main/S04_IA_ADS_KNN_titanic_live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, classification_report
from sklearn.preprocessing import StandardScaler

In [14]:
import pandas as pd

df = pd.read_csv('/content/titanic.csv')
print("DataFrame 'df' carregado com sucesso:")
display(df.head())

DataFrame 'df' carregado com sucesso:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
#Selecionar
df = df [["Survived", "Sex", "Age", "Fare", "Pclass", "SibSp", "Parch"]]

#tratamento
print(df.head(10))

   Survived     Sex   Age     Fare  Pclass  SibSp  Parch
0         0    male  22.0   7.2500       3      1      0
1         1  female  38.0  71.2833       1      1      0
2         1  female  26.0   7.9250       3      0      0
3         1  female  35.0  53.1000       1      1      0
4         0    male  35.0   8.0500       3      0      0
5         0    male   NaN   8.4583       3      0      0
6         0    male  54.0  51.8625       1      0      0
7         0    male   2.0  21.0750       3      3      1
8         1  female  27.0  11.1333       3      0      2
9         1  female  14.0  30.0708       2      1      0

In [16]:
df.head(10)

   Survived     Sex   Age     Fare  Pclass  SibSp  Parch
0         0    male  22.0   7.2500       3      1      0
1         1  female  38.0  71.2833       1      1      0
2         1  female  26.0   7.9250       3      0      0
3         1  female  35.0  53.1000       1      1      0
4         0    male  35.0   8.0500       3      0      0
5         0    male   NaN   8.4583       3      0      0
6         0    male  54.0  51.8625       1      0      0
7         0    male   2.0  21.0750       3      3      1
8         1  female  27.0  11.1333       3      0      2
9         1  female  14.0  30.0708       2      1      0

In [17]:
from numpy import int64
# Conversão de variaveis categoricas
df['masculino'] = pd.get_dummies(df['Sex'], drop_first=True, dtype=int64)

df = pd.get_dummies(df, columns=['Pclass'], prefix='Pclass', drop_first=False, dtype=int64)



df.head(5)

,Survived,Sex,Age,Fare,SibSp,Parch,masculino,Pclass_1,Pclass_2,Pclass_3
0,0,male,22.0,7.2500,1,0,1,0,0,1
1,1,female,38.0,71.2833,1,0,0,1,0,0
2,1,female,26.0,7.9250,0,0,0,0,0,1
3,1,female,35.0,53.1000,1,0,0,1,0,0
4,0,male,35.0,8.0500,0,0,1,0,0,1

In [18]:
# Discretização de variavis continuas

bins = [0, 12, 18, 50, 100]
labels = ['Crianca', 'Adolescente', 'Adulto', 'Idoso']
df['faixaEtaria'] = pd.cut(df['Age'], bins=bins, labels=labels)


bins = [0, 7.91, 14.454, 31, 512] # Limites de tarifas
labels = ['Low Fare', 'Mid-Low Fare', 'Mid-High Fare', 'High Fare']
df['faixaTarifas'] = pd.cut(df['Fare'], bins=bins, labels=labels)

df = pd.get_dummies(
    df,
    columns=['faixaEtaria', 'faixaTarifas'],
    drop_first=True,
    dtype=int64
)

In [19]:
# Definir as variais de entrada de saida

x = df.drop(columns=["Survived", "Sex", "Age", "Fare"])
y = df["Survived"]

In [20]:
#Separar em conjuntos de treimanemtno e teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [21]:
# Padronizar os dados
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [22]:
#Treinar o modelo de regressão logistica
modelo = KNeighborsClassifier(n_neighbors=5)
modelo.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [23]:
#fazer as previsões
y_pred = modelo.predict(x_test_scaled)

In [24]:
 # Avaliação do modelo
print("Matriz de confusão:")
print(confusion_matrix(y_test, y_pred))

print("Acurácia")
print(accuracy_score(y_test, y_pred))

print("Relatorio de classificação")
print(classification_report(y_test, y_pred))

Matriz de confusão:
[[93 12]
 [22 52]]
Acurácia
0.8100558659217877
Relatorio de classificação
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       105
           1       0.81      0.70      0.75        74

    accuracy                           0.81       179
   macro avg       0.81      0.79      0.80       179
weighted avg       0.81      0.81      0.81       179

In [28]:
# Testar com diferentes valores de k
print("K Acurácia")
for k in range(1,20):
  modelo = KNeighborsClassifier(n_neighbors=k)
  modelo.fit(x_train_scaled, y_train)
  y_pred = modelo.predict(x_test_scaled)
  print(f"{k}: {accuracy_score(y_test, y_pred)}")

K Acurácia
1: 0.7821229050279329
2: 0.776536312849162
3: 0.8156424581005587
4: 0.7988826815642458
5: 0.8100558659217877
6: 0.7877094972067039
7: 0.7988826815642458
8: 0.7821229050279329
9: 0.8156424581005587
10: 0.8044692737430168
11: 0.8156424581005587
12: 0.7877094972067039
13: 0.770949720670391
14: 0.7486033519553073
15: 0.7597765363128491
16: 0.7486033519553073
17: 0.776536312849162
18: 0.7821229050279329
19: 0.7653631284916201